# Generated by Django 2.2.5 on 2020-10-12 10:39

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('E_Commerce', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'get_latest_by': 'modified'},
        ),
        migrations.AddField(
            model_name='customer',
            name='created',
            field=django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, default="2020-10-12", verbose_name='created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='modified',
            field=django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified'),
        ),
    ]
