# Generated by Django 2.2.5 on 2020-10-12 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('E_Commerce', '0003_store_vendor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='E_Commerce.VENDOR'),
        ),
    ]
