from django.contrib import admin
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, ),
    path('accounts/customer', views.account),
    path('accounts/signup', views.signup),
    path('cart', views.cart),
    path('welcome', views.welcome),
    path('storesetup', views.store_setup),
    path('paymentsetup', views.payment_setup),
    path('ready', views.ready),
    path('activate/<uidb64>/<token>/', views.activate, name='activate'),
    path('accounts/login', views.login),
    path('accounts/activation_email/<username>/', views.activation_email),
    path('accounts/lost-password', views.lost_password),
    path('accounts/emailpassword', views.lost_password_email),
    path('accounts/reset-password/<username>/', views.reset_password),
    path('accounts/orders', views.orders),
    path('accounts/downloads', views.downloads),
    path('accounts/addresses', views.addresses),
    path('accounts/account-details', views.account_details),
    path('accounts/rma-requests', views.rma_requests),
    path('accounts/vendors', views.vendors),
    path('accounts/tickets', views.tickets),
    path('password_reset/<uidb64>/<token>/', views.password_reset, name='password_reset'),
    path('accounts/reset-password/<username>/new-password', views.new_password),
    path('accounts/vendor', views.vendorAccount),
    path('accounts/login-vendor', views.login_vendor),
    path('accounts/signup-vendor', views.signup_vendor),
    path('accounts/activation_email/vendor/<username>/', views.activation_email_vendor),
    path('activate_vendor/<uidb64>/<token>/', views.activate_vendor, name='activate_vendor'),
    path('accounts/lost-password-vendor', views.lost_password_vendor),
    path('accounts/vendorpassword', views.lost_password_email_vendor),
    path('password_reset_vendor/<uidb64>/<token>/', views.password_reset_vendor, name='password_reset_vendor'),
    path('accounts/reset-password-vendor/<username>/', views.reset_password_vendor),
    path('accounts/reset-password-vendor/<username>/new-password-vendor', views.new_password_vendor),
]
